import React from 'react';

export interface HadarsImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
    src: string;
    alt: string;
    /**
     * Pixel widths to include in the `srcset`. Must match (or be a subset of)
     * the `images.widths` configured in `hadars.config.ts`.
     * Default: `[640, 1280, 1920]`.
     */
    widths?: number[];
    /**
     * Formats to offer, in preference order (most-preferred first).
     * Browsers pick the first format they support.
     * Default: `['webp']`.
     */
    formats?: ('webp' | 'avif')[];
    /**
     * `sizes` attribute forwarded to both `<source>` and the fallback `<img>`.
     * Default: `'100vw'`.
     */
    sizes?: string;
}

const FORMAT_MIME: Record<string, string> = {
    webp: 'image/webp',
    avif: 'image/avif',
};

/**
 * Responsive image component.
 *
 * Renders a `<picture>` element with `<source>` elements pointing at the
 * build-time variants generated by `hadars build` or `hadars export static`.
 * Variants are served from `/_images/<src-without-ext>-<width>.<format>`.
 *
 * Configure variant generation in `hadars.config.ts`:
 * ```ts
 * import type { HadarsOptions } from 'hadars';
 * export default {
 *   images: { widths: [640, 1280, 1920], formats: ['webp', 'avif'], quality: 85 },
 * } satisfies HadarsOptions;
 * ```
 *
 * Falls back to the original `src` for browsers without `<picture>` support,
 * and always sets `loading="lazy"` and `decoding="async"` unless overridden.
 *
 * @example
 * <HadarsImage
 *   src="/photos/hero.jpg"
 *   alt="A scenic mountain view"
 *   widths={[640, 1280, 1920]}
 *   sizes="(max-width: 768px) 100vw, 50vw"
 * />
 */
export function HadarsImage({
    src,
    alt,
    widths = [640, 1280, 1920],
    formats = ['webp'],
    sizes = '100vw',
    loading = 'lazy',
    decoding = 'async',
    ...rest
}: HadarsImageProps): React.ReactElement {
    const dotIdx = src.lastIndexOf('.');
    const srcNoExt = dotIdx !== -1 ? src.slice(0, dotIdx) : src;
    // Variants live at /_images/<original-path-without-ext>-<width>.<format>
    const imgBase = '/_images' + srcNoExt;

    const buildSrcSet = (fmt: string) =>
        widths.map(w => `${imgBase}-${w}.${fmt} ${w}w`).join(', ');

    // avif (smallest) before webp before others — browser picks first supported.
    const orderedFormats = [...formats].sort((a, b) => {
        const rank: Record<string, number> = { avif: 0, webp: 1 };
        return (rank[a] ?? 2) - (rank[b] ?? 2);
    });

    return (
        <picture>
            {orderedFormats.map(fmt => (
                <source
                    key={fmt}
                    type={FORMAT_MIME[fmt] ?? `image/${fmt}`}
                    srcSet={buildSrcSet(fmt)}
                    sizes={sizes}
                />
            ))}
            <img
                src={src}
                alt={alt}
                loading={loading}
                decoding={decoding}
                sizes={sizes}
                {...rest}
            />
        </picture>
    );
}
