/**
 * Bunny.net Edge Scripting adapter for hadars.
 *
 * After running `hadars build`, bundle your app with:
 *
 *   hadars export bunny
 *
 * This produces a self-contained `bunny.mjs` that you deploy to
 * bunny.net Edge Scripting (Standalone script type).
 *
 * Static assets (JS, CSS, fonts) under `.hadars/static/` must be served from
 * bunny.net Storage or another CDN — the edge script only handles HTML
 * rendering. Route requests for static file extensions to Storage and
 * everything else to the script.
 *
 * The runtime is Deno + Web APIs. The script calls
 * `BunnySDK.net.http.serve()` which is the bunny.net equivalent of
 * Cloudflare's `export default { fetch }`.
 *
 * @example bunny script entry (generated by `hadars export bunny`)
 *   import * as BunnySDK from "@bunny.net/edgescript-sdk";
 *   import * as ssrModule from './.hadars/index.ssr.js';
 *   import outHtml from './.hadars/static/out.html';
 *   import { createBunnyHandler } from 'hadars/bunny';
 *   import config from './hadars.config';
 *   BunnySDK.net.http.serve(createBunnyHandler(config, { ssrModule, outHtml }));
 */

import React from 'react';
import { parseRequest } from './utils/request';
import { createProxyHandler } from './utils/proxyHandler';
import { getReactResponse, buildHeadHtml } from './utils/response';
import { buildSsrHtml, makePrecontentHtmlGetter, createRenderCache } from './utils/ssrHandler';
import type { HadarsOptions, HadarsEntryModule, HadarsProps } from './types/hadars';

// ── Public types ──────────────────────────────────────────────────────────────

/**
 * Pre-loaded SSR module and HTML template for single-file Bunny bundles
 * produced by `hadars export bunny`. All I/O is eliminated at runtime —
 * the edge script is fully self-contained.
 */
export interface BunnyBundled {
    /** The compiled SSR module — import it statically in your entry shim. */
    ssrModule: HadarsEntryModule<any>;
    /**
     * The contents of `.hadars/static/out.html` — esbuild inlines this as a
     * string when `hadars export bunny` runs.
     */
    outHtml: string;
}

// ── Handler factory ───────────────────────────────────────────────────────────

/**
 * Creates a Bunny.net Edge Scripting handler from a hadars config and a
 * pre-bundled SSR module, and immediately registers it with
 * `BunnySDK.net.http.serve`.
 *
 * Unlike the Lambda adapter, Bunny edge scripts receive a standard Web
 * `Request` and return a standard `Response`, matching the Cloudflare
 * Workers interface. Static assets must be routed to bunny.net Storage/CDN;
 * the script handles only HTML rendering and API routes.
 *
 * @example — generated entry shim (created by `hadars export bunny`)
 * import * as BunnySDK from "@bunny.net/edgescript-sdk";
 * import * as ssrModule from './.hadars/index.ssr.js';
 * import outHtml from './.hadars/static/out.html';
 * import { createBunnyHandler } from 'hadars/bunny';
 * import config from './hadars.config';
 * BunnySDK.net.http.serve(createBunnyHandler(config, { ssrModule, outHtml }));
 */
export function createBunnyHandler(
    options: HadarsOptions,
    bundled: BunnyBundled,
): (request: Request) => Promise<Response> {
    const fetchHandler      = options.fetch;
    const handleProxy       = createProxyHandler(options);
    const getPrecontentHtml = makePrecontentHtmlGetter(Promise.resolve(bundled.outHtml));
    const { ssrModule }     = bundled;

    const runHandler = async (req: Request): Promise<Response> => {
        const request = parseRequest(req);

        if (fetchHandler) {
            const res = await fetchHandler(request);
            if (res) return res;
        }

        const proxied = await handleProxy(request);
        if (proxied) return proxied;

        try {
            const { default: Component, getInitProps, getFinalProps } = ssrModule;

            const isDataOnly = request.headers.get('Accept') === 'application/json';
            const { head, status, getAppBody, finalize } = await getReactResponse(request, {
                document: {
                    body: Component as React.FC<HadarsProps<object>>,
                    lang: 'en',
                    getInitProps,
                    getFinalProps,
                },
                singlePass: !isDataOnly,
                dataOnly: isDataOnly,
            });

            // Data-only requests from client-side navigation.
            if (isDataOnly) {
                const { clientProps } = await finalize();
                const serverData = (clientProps as any).__serverData ?? {};
                return new Response(JSON.stringify({ serverData }), {
                    status,
                    headers: { 'Content-Type': 'application/json; charset=utf-8' },
                });
            }

            const bodyHtml = await getAppBody();
            const { clientProps } = await finalize();
            const headHtml = buildHeadHtml(head);
            const html = await buildSsrHtml(bodyHtml, clientProps, headHtml, getPrecontentHtml);

            return new Response(html, {
                status,
                headers: { 'Content-Type': 'text/html; charset=utf-8' },
            });
        } catch (err: any) {
            console.error('[hadars] SSR render error:', err);
            options.onError?.(err, request)?.catch?.(() => {});
            return new Response('Internal Server Error', { status: 500 });
        }
    };

    const finalHandler = options.cache
        ? createRenderCache(options.cache, (req) => runHandler(req))
        : (req: Request) => runHandler(req);

    return async (request: Request): Promise<Response> => {
        return (await finalHandler(request, undefined)) ?? new Response('Not Found', { status: 404 });
    };
}
